/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./../../packages/components/src/button/button.vue')['default']
    Input: typeof import('./../../packages/components/src/input/input.vue')['default']
  }
}

// For TSX support
declare global {
  const Button: typeof import('./../../packages/components/src/button/button.vue')['default']
  const Input: typeof import('./../../packages/components/src/input/input.vue')['default']
}