/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./../../packages/src/components/button/button.vue')['default']
    Input: typeof import('./../../packages/src/components/input/input.vue')['default']
    Search: typeof import('./../../packages/src/components/search/search.vue')['default']
    Select: typeof import('./../../packages/src/components/select/select.vue')['default']
    Title: typeof import('./../../packages/src/businessComponents/title/title.vue')['default']
  }
}

// For TSX support
declare global {
  const Button: typeof import('./../../packages/src/components/button/button.vue')['default']
  const Input: typeof import('./../../packages/src/components/input/input.vue')['default']
  const Search: typeof import('./../../packages/src/components/search/search.vue')['default']
  const Select: typeof import('./../../packages/src/components/select/select.vue')['default']
  const Title: typeof import('./../../packages/src/businessComponents/title/title.vue')['default']
}